// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_zd022CyxRZQjmfmQ7CUE0OJkfpINOcY',
    appId: '1:169927258971:web:f0786ede36d98e8019207e',
    messagingSenderId: '169927258971',
    projectId: 'say-hii-3b5e9',
    authDomain: 'say-hii-3b5e9.firebaseapp.com',
    storageBucket: 'say-hii-3b5e9.appspot.com',
    measurementId: 'G-C6PRMTH4Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTof3owFWLoLmY5ET-hwhKkkfOlbmbDA',
    appId: '1:169927258971:android:32ec1643f48be7e019207e',
    messagingSenderId: '169927258971',
    projectId: 'say-hii-3b5e9',
    storageBucket: 'say-hii-3b5e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMNxgToVSj3_Sdjj7wuoRAdJFrHKuUBTk',
    appId: '1:169927258971:ios:81ac4b282d9cb52619207e',
    messagingSenderId: '169927258971',
    projectId: 'say-hii-3b5e9',
    storageBucket: 'say-hii-3b5e9.appspot.com',
    androidClientId: '169927258971-4h9gp1ifcrepkav33t7cdgbpaue6eatc.apps.googleusercontent.com',
    iosClientId: '169927258971-mq9ht3338tj4pcvsfk1flfr13jquiqak.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMNxgToVSj3_Sdjj7wuoRAdJFrHKuUBTk',
    appId: '1:169927258971:ios:7a78c35fc9083ecc19207e',
    messagingSenderId: '169927258971',
    projectId: 'say-hii-3b5e9',
    storageBucket: 'say-hii-3b5e9.appspot.com',
    androidClientId: '169927258971-4h9gp1ifcrepkav33t7cdgbpaue6eatc.apps.googleusercontent.com',
    iosClientId: '169927258971-dmag7r1plpunnorend0npdguvikjutp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
